/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const OrderStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'rejected' : IDL.Null,
});
export const Time = IDL.Int;
export const Order = IDL.Record({
  'status' : OrderStatus,
  'username' : IDL.Text,
  'screenshotUrl' : IDL.Text,
  'minecraftUsername' : IDL.Text,
  'timestamp' : Time,
  'itemName' : IDL.Text,
  'price' : IDL.Text,
});
export const CoinPackageConfig = IDL.Record({
  'perks' : IDL.Vec(IDL.Text),
  'price' : IDL.Text,
  'amount' : IDL.Nat,
  'packageLabel' : IDL.Text,
});
export const RankConfig = IDL.Record({
  'name' : IDL.Text,
  'perks' : IDL.Vec(IDL.Text),
  'price' : IDL.Text,
});
export const SiteConfig = IDL.Record({
  'discordLink' : IDL.Text,
  'serverIp' : IDL.Text,
  'coinPackages' : IDL.Vec(CoinPackageConfig),
  'ranks' : IDL.Vec(RankConfig),
});
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'email' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'adminDeleteOrder' : IDL.Func([IDL.Nat], [], []),
  'adminGetAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'adminGetOrderCount' : IDL.Func([], [IDL.Nat], ['query']),
  'adminGetSiteConfig' : IDL.Func([], [SiteConfig], ['query']),
  'adminGetUsers' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
      ['query'],
    ),
  'adminUpdateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
  'adminUpdateSiteConfig' : IDL.Func([SiteConfig], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPublicSiteConfig' : IDL.Func([], [SiteConfig], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitOrder' : IDL.Func([Order], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const OrderStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const Time = IDL.Int;
  const Order = IDL.Record({
    'status' : OrderStatus,
    'username' : IDL.Text,
    'screenshotUrl' : IDL.Text,
    'minecraftUsername' : IDL.Text,
    'timestamp' : Time,
    'itemName' : IDL.Text,
    'price' : IDL.Text,
  });
  const CoinPackageConfig = IDL.Record({
    'perks' : IDL.Vec(IDL.Text),
    'price' : IDL.Text,
    'amount' : IDL.Nat,
    'packageLabel' : IDL.Text,
  });
  const RankConfig = IDL.Record({
    'name' : IDL.Text,
    'perks' : IDL.Vec(IDL.Text),
    'price' : IDL.Text,
  });
  const SiteConfig = IDL.Record({
    'discordLink' : IDL.Text,
    'serverIp' : IDL.Text,
    'coinPackages' : IDL.Vec(CoinPackageConfig),
    'ranks' : IDL.Vec(RankConfig),
  });
  const UserProfile = IDL.Record({ 'username' : IDL.Text, 'email' : IDL.Text });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'adminDeleteOrder' : IDL.Func([IDL.Nat], [], []),
    'adminGetAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'adminGetOrderCount' : IDL.Func([], [IDL.Nat], ['query']),
    'adminGetSiteConfig' : IDL.Func([], [SiteConfig], ['query']),
    'adminGetUsers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
        ['query'],
      ),
    'adminUpdateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
    'adminUpdateSiteConfig' : IDL.Func([SiteConfig], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPublicSiteConfig' : IDL.Func([], [SiteConfig], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitOrder' : IDL.Func([Order], [], []),
  });
};

export const init = ({ IDL }) => { return []; };