/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CoinPackageConfig {
  'perks' : Array<string>,
  'price' : string,
  'amount' : bigint,
  'packageLabel' : string,
}
export interface Order {
  'status' : OrderStatus,
  'username' : string,
  'screenshotUrl' : string,
  'minecraftUsername' : string,
  'timestamp' : Time,
  'itemName' : string,
  'price' : string,
}
export type OrderStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'rejected' : null };
export interface RankConfig {
  'name' : string,
  'perks' : Array<string>,
  'price' : string,
}
export interface SiteConfig {
  'discordLink' : string,
  'serverIp' : string,
  'coinPackages' : Array<CoinPackageConfig>,
  'ranks' : Array<RankConfig>,
}
export type Time = bigint;
export interface UserProfile { 'username' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'adminDeleteOrder' : ActorMethod<[bigint], undefined>,
  'adminGetAllOrders' : ActorMethod<[], Array<Order>>,
  'adminGetOrderCount' : ActorMethod<[], bigint>,
  'adminGetSiteConfig' : ActorMethod<[], SiteConfig>,
  'adminGetUsers' : ActorMethod<[], Array<[Principal, UserProfile]>>,
  'adminUpdateOrderStatus' : ActorMethod<[bigint, OrderStatus], undefined>,
  'adminUpdateSiteConfig' : ActorMethod<[SiteConfig], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPublicSiteConfig' : ActorMethod<[], SiteConfig>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitOrder' : ActorMethod<[Order], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];